name: Deploy to Linux Server

on:
    push:
      branches:
        - main # The branch to trigger the deployment when you push a commit to it
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # If you are using Nginx server
    environment: Development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Ensure Node.js version is compatible with your Angular project

      - name: Install dependencies
        run: |
            run: |
            if [ -e yarn.lock ]; then
                yarn install --frozen-lockfile
            elif [ -e package-lock.json ]; then
                npm ci
            else
                npm i
            fi

      - name: Install Angular CLI
        run: npm install -g @angular/cli # Install Angular CLI in the workflow environment

      - name: Build Angular app
        run: ng build --configuration production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: angular_deploy_dist
          path: ${{ github.workspace }}/dist

  deploy:
    runs-on: ubuntu-latest # If you are using Nginx server
    environment: Development
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: angular_deploy_dist

      - name: Remove Files on Nginx Server
        uses: appleboy/ssh-action@master
        env:
          AZURE_VM_ADMINISTRATOR : ${{ secrets.AZURE_VM_ADMINISTRATOR }}
          AZURE_VM_IP_ADDRESS : ${{ secrets.AZURE_VM_IP_ADDRESS }}
          AZURE_VM_SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
        with:
          # SSH host address.
          host: ${{ env.AZURE_VM_IP_ADDRESS }}
          # SSH username.
          username: ${{ env.AZURE_VM_ADMINISTRATOR }}
          # Path to the SSH private key file.
          key: ${{ env.AZURE_VM_SSH_PRIVATE_KEY}}
          # Commands to be executed.
          script: |
            mkdir -p testapplication
            rm -rf testapplication/*

      - name: Check Download Artifact
        run: |
          cd ${{ github.workspace }}
          ls

      - name: Deploy Files to Nginx Server
        uses: appleboy/scp-action@master
        env:
          AZURE_VM_ADMINISTRATOR : ${{ secrets.AZURE_VM_ADMINISTRATOR }}
          AZURE_VM_IP_ADDRESS : ${{ secrets.AZURE_VM_IP_ADDRESS }}
          AZURE_VM_SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
        with:
          # SSH host address.
          host: ${{ env.AZURE_VM_IP_ADDRESS }}
          # SSH username.
          username: ${{ env.AZURE_VM_ADMINISTRATOR }}
          # Path to the SSH private key file.
          key: ${{ env.AZURE_VM_SSH_PRIVATE_KEY}}
          source: '${{ github.workspace }}/angular_deploy_dist/*'
          target: 'testapplication' # Specify the path of the target folder on the server (e.g., /var/www/html/front/)
          strip_components: 2# Removes a specified number of directory components (folders) from the beginning of a file path.
                              # This can be used to deploy only specific folders and files.
